name: Save figures

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Make new file
      run: |
        echo "Good stuff!" > newfile.txt
    - name: Upload file
      uses: actions/upload-artifact@v1
      with:
        name: New file
        path: newfile.txt
    - name: Print some numbers from numpy
      shell: bash
      run: |
        apt-get update -qqy && apt-get install -qqy make clang curl gcc g++ 
        python -m pip install numpy pandas scipy wheel
        python print_numbers.py
    - name: Upload figure
      uses: actions/upload-artifact@v1
      with:
        name: Figure
        path: test.png
