name: Save figures

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Make new file
      run: |
        echo "Good stuff!" > newfile.txt
    - name: Upload file
      uses: actions/upload-artifact@v1
      with:
        name: New file
        path: newfile.txt
    - name: Print some numbers from numpy
      shell: bash
      run: |
        python -m pip install numpy pandas scipy
        python print_numbers.py
    - name: Upload CSV
      uses: actions/upload-artifact@v1
      with:
        name: CSV file
        path: test.csv
