name: Save figures

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Make new file
      run: |
        mkdir output_files
        echo "Good stuff!" > output_files/newfile.txt
    - name: Run numpy
      run: |
        python -m pip install numpy pandas scipy
        python print_numbers.py
    - name: Upload folder
      uses: actions/upload-artifact@v1
      with:
        name: output_file
        path: output_file
