name: Saver

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build container
      run:  docker build --tag test -f Dockerfile .
    - name: run tests
      run: docker run test
    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: New file
        path: newfile.txt

